title: Amirhossein Amini
description: Transformers · ICL/CoT · Training Dynamics
theme: minima
# Set your GitHub handle to enable Minima's social links:
github_username: Amir-Hussen
# Optional: add Google Analytics / Cloudflare later